### ISSUE TITLE
User interaction events watcher should be optional

### ISSUE THREAD

**Issue by korbav** [foobar404/Wave.js#11]
Waiting for user events might be a must when the visualizer is loaded as soon as the page is loaded.

But, when using it with one-page apps frameworks, the user might have already interacted with the browser before the Visualizer is loaded, which will result in waiting uselessly for a user event before rendering the canvas.

The code that handles that : 
```
if (this.activated) {
        run.call(waveContext);
    } else {
        //wait for a valid user gesture 
        document.body.addEventListener("touchstart", create, { once: true });
        document.body.addEventListener("touchmove", create, { once: true });
        document.body.addEventListener("touchend", create, { once: true });
        document.body.addEventListener("mouseup", create, { once: true });
        document.body.addEventListener("click", create, { once: true });
        element.addEventListener("play", create, { once: true });
    }
```

My suggestion is to add a boolean option `waitForUserInteractionBeforeRendering`, default to `true`, if false, then don't wait for anything.

**Comment by foobar404** [comment]
Okay ill try to handle that, feel free to make a pull request with the changes.

**Comment by korbav** [comment]
> 
> 
> Okay ill try to handle that, feel free to make a pull request with the changes.

PR created here https://github.com/foobar404/Wave.js/pull/12
