### ISSUE TITLE
wave.fromStream is broken

### ISSUE THREAD

**Issue by yulius-take2** [foobar404/Wave.js#18]
https://github.com/foobar404/Wave.js/blob/master/src/fromStream.js#L38

`frameCount` is not passed in if you use `wave.fromStream`

**Comment by Avadakedvr** [comment]
any fixes to this ? the fromStream method doesn't work for me either...

**Comment by codingyourlife** [comment]
damn this is the reason...

**Comment by korbav** [comment]
> 
> 
> damn this is the reason...

Could you please give a try to the master branch of my rewrite to see if it fixed your problem, we might, hopefully, integrate this in this repo later?
[https://github.com/foobar404/Wave.js/issues/27](https://github.com/foobar404/Wave.js/issues/27)

**Comment by zipelkopf** [comment]
Hi, not sure if I missed anything, but I'm trying `wave.fromStream` using the master branch and it still does not work using the basic example from the README.

Any update, please? Thanks

```html
<html>

<head></head>

<body>

   <canvas id="output" height="500" width="500"></canvas>

   <script src="https://cdn.jsdelivr.net/gh/foobar404/wave.js/dist/bundle.iife.js"></script>
   <script>
      let wave = new Wave();

      navigator.mediaDevices.getUserMedia({
            audio: true
         })
         .then(function (stream) {
            wave.fromStream(stream, "output", {
               type: "shine",
               colors: ["red", "white", "blue"]
            });
         })
         .catch(function (err) {
            console.log(err.message)
         });
   </script>
</body>

</html>
```

**Comment by ftr9** [comment]
this seems to work perfectly
as soon as we get stream from getUserMedia()
1. create the audio element **=>** const audio = document.createElement('audio')
2. set the id attribute of audio element **=>** audio.setAttribute('id', 'audios')
3. set the source of audio element by providing our stream **=>** audio.srcObject= stream
4. provide controls just to play around  **=>** audio.controls = true
5. add listener to audio element as soon as the audio element is ready play the audio **=>**
 audio.addEventListener('loadedmetadata', () => {
    audio.play()
 })
6.finally append that audio element to body  => document.querySelector('body').append(audio)
7.use wave.fromElement =>wave.fromElement('audios', 'output', { type: 'shine',colors: ['red', 'white', 'blue']})

**here is the working code** 

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <canvas id="output" height="500" width="500"></canvas>
    
    <script src="https://cdn.jsdelivr.net/gh/foobar404/wave.js/dist/bundle.iife.js"></script>
    <script>
      const wave = new Wave()

      //request user for media devices
      navigator.mediaDevices
        .getUserMedia({
          audio: true,
        })
        .then(stream => {
          const audio = document.createElement('audio')
          audio.setAttribute('id', 'audios')
          //set the stream to audio element's source object
          audio.srcObject = stream
          audio.controls = true

          audio.addEventListener('loadedmetadata', () => {
            audio.play()
          })

          //append to body
          document.querySelector('body').append(audio)

          //generate wave
          wave.fromElement('audios', 'output', {
            type: 'shine',
            colors: ['red', 'white', 'blue'],
          })
        })
    </script>
  </body>
</html>

**Comment by ftr9** [comment]
this seems to work perfectly
as soon as we get stream from getUserMedia()

    1.create the audio element => const audio = document.createElement('audio')
    2.set the id attribute of audio element => audio.setAttribute('id', 'audios')
    3.set the source of audio element by providing our stream => audio.srcObject= stream
    4.provide controls just to play around => audio.controls = true
    5.add listener to audio element as soon as the audio element is ready to play the audio =>
    audio.addEventListener('loadedmetadata', () => {
    audio.play()
    })
    6.finally append that audio element to body => document.querySelector('body').append(audio)
    7.use wave.fromElement =>wave.fromElement('audios', 'output', { type: 'shine',colors: ['red', 'white', 'blue']})

here is the working code.....
![image](https://user-images.githubusercontent.com/60734475/150693408-40147432-e296-4625-9821-c5065275ae20.png)
