### ISSUE TITLE
When drawing a wave, keep already drawn elements on canvas.

### ISSUE THREAD

**Issue by iamanas20** [foobar404/Wave.js#19]
Hey @foobar404, thanks for this amazing library!

When using the `fromElement` function it seems that it removes elements already drawn on the canvas and displays the wave. Is there an option to keep those elements and draw the wave on top of them?

Also, can we change the wave's positions using options?

**Comment by foobar404** [comment]
Based on how the context API works, I dont think I can draw the wave on top of the other graphics, you could make 2 canvases that overlap. As for moving the position of the wave, that is possible, but not implemented yet.

**Comment by iamanas20** [comment]
That's exactly what I did. Thanks!
