### ISSUE TITLE
How do i get rid of the background. 

### ISSUE THREAD

**Issue by johnlandish** [foobar404/Wave.js#2]
I want to put the waveform in a video?

**Comment by PiethonCoder** [comment]
The waveform needs  a canvas elm to be rendered. You can capture a stream of the canvas with the captureStream function and add that to a video object to see the output. 

var canvas = document.getElementById("c");
var stream = canvas.captureStream(25);

var video = document.getElementById("v");
video.srcObject = stream;

**Comment by johnlandish** [comment]
Thanks, How do i edit the design of the waveforms?
