### ISSUE TITLE
Doesn't work randomly in "Android Chrome"

### ISSUE THREAD

**Issue by cincarnato** [foobar404/Wave.js#20]
I am working on a project with a "Words Picture Gallery". When you click on one Word/Picture the webapp play  "the word sound" (a mp3 file) and show the bars wave using "foobar404/wave".

On desktop this works 100%, but in Android Chrome, randomly doesnt work and when this happens, the wave library do a "INIFINITY LOOP" over the renderFrame function, I notice this put some console log in "renderFrame" function.

Also, when this happens, a console.log on variable "data" show this:

Uint8Array(1024) [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …]

Also, the event "ended" on the audio element never fires

**Comment by cincarnato** [comment]
After a while debuging I figure out whats happens. There are some limitations in the quantity of AudioContext that you can run at the same time.

I made a fork of the project, and add a way to do a AudioContext.close() and works like a charm!

see: https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/close

**Comment by korbav** [comment]
Hi @cincarnato , nice to read you found a solution to your problem. Just for clarification purpose, was your problem related to the fact you were running multiple instances of the Visualizer simultaneously, or is something else?

**Comment by cincarnato** [comment]
Yes, I run multiple instances, and I notice that was not a random problem, the instance number 10 fails because AudioContext reached its limits number of instance.
