### ISSUE TITLE
.

### ISSUE THREAD

**Issue by iamanas20** [foobar404/Wave.js#22]
.

**Comment by foobar404** [comment]
Not right now, I'm not sure how you would implement it into a node app because there isint anything to display the visuals on.

**Comment by iamanas20** [comment]
Gonna be using [node-canvas](https://github.com/Automattic/node-canvas) for it.

**Comment by iamanas20** [comment]
So I took inspiration from this [repo](https://github.com/victordibia/beats) and used node-canvas to create png file of the wave.
