### ISSUE TITLE
Ability to visualise muted audio

### ISSUE THREAD

**Issue by Avadakedvr** [foobar404/Wave.js#23]
In some circumstances, it is useful to visualise audio, but mute/set volume to 0 to not hear it at the same time. Please consider adding this feature or the ability to control the volume of the audio that is being visualised. I've tried to set the volume of the audio object I'm passing to "fromElement" but no luck - I can still hear myself (visualising my microphone input).

**Comment by korbav** [comment]
Hi, have you tried to call fromStream with `{ connectDestination: false }` ?

```
navigator.mediaDevices.getUserMedia({
  audio: true,
}).then((stream) => {
    wave.fromStream(
        stream,
        "canvas-id",
        {
            type: "bars",
            connectDestination: false
        }
    );
);
```

**Comment by samuelkarani** [comment]
using   `connectDestination: false` doesn't seem to work now

**Comment by polomoshnov** [comment]
For the interested here's a way to accomplish that: https://github.com/foobar404/Wave.js/issues/67
