### ISSUE TITLE
React example doesn't work

### ISSUE THREAD

**Issue by m1yon** [foobar404/Wave.js#28]
The React example inside `test/react-test` doesn't work. The audio player works and I can hear/control the audio, but nothing is rendered to the canvas.

I've tried running it in both with the latest versions of Chrome and Firefox with the same result.

**Comment by vitrioil** [comment]
I am confused, it seems that fromElement requires the id of the canvas and the audio. But the output of querySelector is passed in?

I guess something like this solves it:

```js
wave.fromElement("audio", "canvas", { type: "star" })
```
```html
<audio id="audio"...
```

**Comment by acroyear** [comment]
it looks like it takes both the id or the element directly.
