### ISSUE TITLE
Package does not have Angular ng-add support

### ISSUE THREAD

**Issue by Electrenator** [foobar404/Wave.js#41]
Wave.js doesn't seem to have ng-add support for Angular. This is making it difficult to use with Angular, especially since this package can't be recognized by Angular even after an NPM install. 
```txt
Error: src/app/components/posts/record/record.component.ts:7:20 - error TS7016: Could not find a declaration file for module '@foobar404/wave'. '/home/electrenator/Documents/Code/[redacted]/front-end/node_modules/@foobar404/wave/dist/bundle.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/foobar404__wave` if it exists or add a new declaration (.d.ts) file containing `declare module '@foobar404/wave';`

7 import {Wave} from '@foobar404/wave';
                     ~~~~~~~~~~~~~~~~~
 ```
 
I installed this package via the Angular CLI. This yields the same result as installing it via NPM. My install log:
 ```txt
$ ng add @foobar404/wave
ℹ Using package manager: npm
✔ Found compatible package version: @foobar404/wave@1.2.7.
✔ Package information loaded.
 
The package @foobar404/wave@1.2.7 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```
Currently I can't figure out how I can still use this package within my project. It would be nice if I would be able too :)

### Software versions
Angular CLI: 12.2.13
Node: 12.21.0
Package Manager: npm 8.1.3
OS: linux x64
typescript: 4.3.5

**Comment by foobar404** [comment]
ah this might not work because the library wasint written in typescript, someone might of created a typed version in the DefinitelyTyped npm package though, check there.

**Comment by acroyear** [comment]
Here's a .d.ts file.  For me I just created it locally as "WaveModule.d.ts" and it just worked.  I don't know the best way to add a "@something/sometihng" module to DefinitelyTyped, though...maybe I should go find out...
```
type WaveTypes = 'bars' |
    'bars blocks' |
    'big bars' |
    'cubes' |
    'dualbars' |
    'dualbars blocks' |
    'fireworks' |
    'flower' |
    'flower blocks' |
    'orbs' |
    'ring' |
    'rings' |
    'round wave' |
    'shine' |
    'shine rings' |
    'shockwave' |
    'star' |
    'static' |
    'stitches' |
    'web' |
    'wave';


interface WaveOptions {
    stroke?: number;
    colors?: Array<string>;
    type: WaveTypes;
}

declare class Wave {
    constructor() { }
    fromElement: (audioId: string, canvasId: string, options: WaveOptions) => void;
    fromStream: (string: MediaStream, canvasId: string, options: WaveOptions) => void;
    stopStream: () => void;
    fromFile: (file: string, options: WaveOptions) => void;
    // supplied by the client
    onFileLoad?: (imageDataURI: string) => void;
}

declare module "@foobar404/wave" {
    export = Wave
};
```
I don't know the specific type to use for a data-uri (is it just a string?) as I wasn't using that function. Same with the stream, I just tagged that as an any for now.

**Comment by acroyear** [comment]
(yeah, i updated it - didn't see the "take an array of types" until just now, so I adapted)

**Comment by acroyear** [comment]
also, that's only for Wave 1.2.8.  2.0.0 has its own types (though I'm having trouble getting them to be recognized by VSC)

**Comment by foobar404** [comment]
Yea, I get some auto intellisense for visual studio code, but not very much, there are many type files defined for everything in the project, and in the Rider IDE I get pretty good type hints, im not sure how to beef up vscode hints. Also, the types would only work if you use the npm package, if you import the CDN link you wont get any.

**Comment by acroyear** [comment]
for 2.0 - there's a lot there, it just needs to be applied consistently.  first is that the IWaveOptions get moved into types/index.ts (along with any others missing).  Second is root index.ts just needs to `export * from '/.types';`.  Internal typing looks good, just need to be consistent about how it is packaged.

I'll see if I can fork up an MR to help if you like? Dealing with type exporting is something of a hobby of mine in my day job these days.

**Comment by acroyear** [comment]
The code is type-safe in terms of verifying the parameters passed in...but what it can't do is allow you to have type-safety upfront when you try to declare variables of your own to match the type. Instead of telling you what's wrong with your object, it just tells you that it can't get passed in to that property, which is a much harder error message to decipher.

**Comment by acroyear** [comment]
https://github.com/foobar404/Wave.js/pull/61
