### ISSUE TITLE
MediaStream with multiple tracks

### ISSUE THREAD

**Issue by pauzha-lab** [foobar404/Wave.js#5]
hi, 
first.  you did a great work.

am trying to visualize stream with multiple tracks, but visuals are only based on one track (the first track in the stream )
am new to web audio api. i would really appreciate your help.

**Comment by foobar404** [comment]
Okay, im currently working on an updated version so I should be able to fix that soon, to get a bit more information, your using the fromStream function right.

**Comment by pauzha-lab** [comment]
yes, am using fromStream,  ill paste a sample
`stream =  new MediaStream();

stream.addTrack(someAudioTrack);
stream.addTrack(someAudioTrack);

var wave = new Wave();
wave.fromStream(stream, "out_canvas", options)`

**Comment by foobar404** [comment]
okay thanks, I hope to have this issue solved soon.

**Comment by foobar404** [comment]
From what I can tell MediaStreamAudioSourceNode can only have one audio track. "If multiple audio tracks are present on the stream, the track whose id comes first lexicographically (alphabetically) is used." You would have to join the 2 tracks into one before adding to the stream, which im not sure how to do.

**Comment by pauzha-lab** [comment]
thanks for the effort
