### ISSUE TITLE
v2.0 - changes to Wave types

### ISSUE THREAD

**Issue by frankykubo** [foobar404/Wave.js#57]
Hello, I've been using v1.x version of your lib and I was able to make effect like on attached image with Flower type.

![flower_old](https://user-images.githubusercontent.com/50501921/158967226-3fa5aff2-6af8-49ec-a5a4-bc3b6e01fea2.png)

 I wanted to migrate to v 2.0, but effect of flower is completely different. Shine is kind of looking similiar, but:

1. The lines go only outside of diameter
2. When I slide the volume to max, lines are too big and I couldn't fix it with any options

This is old Flower with maximum volume:

![old_flower_max](https://user-images.githubusercontent.com/50501921/158969301-8ac29987-6b4f-4661-963b-a07ffa7a3fe0.png)

This is new Shine with maximum volume:

![shine_max](https://user-images.githubusercontent.com/50501921/158969471-0733172c-1e5e-4d6f-8b22-6605d2d183d5.png)

Do you think I can achieve such effect with v2.0? Or wouldnt be possible to get an option to specify max width / height of the specific animation types somehow?

Thank you.

**Comment by austin-sigparser** [comment]
I can add an option to Shine in the near future that will offset the bars inwards, Currently it cant be done. The reason the animation gets so large when you change the volume is because none of the animations change based on the size of the canvas right now, v.1 use to do that. That will be reimplemented eventually. If you resize your canvas, you will likely see all of the animation.

**Comment by foobar404** [comment]
I can add an option to Shine in the near future that will offset the bars inwards, Currently it cant be done. The reason the animation gets so large when you change the volume is because none of the animations change based on the size of the canvas right now, v.1 use to do that. That will be reimplemented eventually. If you resize your canvas, you will likely see all of the animation.

**Comment by frankykubo** [comment]
> I can add an option to Shine in the near future that will offset the bars inwards, Currently it cant be done. The reason the animation gets so large when you change the volume is because none of the animations change based on the size of the canvas right now, v.1 use to do that. That will be reimplemented eventually. If you resize your canvas, you will likely see all of the animation.

In v 2.0.3 it looks really good on low volume, but if I increase it, it will still blow the lines to sky. Just a question, I looked into the options after update and you didn't yet implemented this option, did you? I cannot make the canvas bigger because of the web design.

**Comment by foobar404** [comment]
@frankykubo you must be using the CDN link, I just checked and for some reason its not updating. Ill have to look into a new CDN service, but the NPM package is up-to-date, and the dist/bundle.js file is updated, if you want to just download that and include it in your project for the short-term.

**Comment by frankykubo** [comment]
> @frankykubo you must be using the CDN link, I just checked and for some reason its not updating. Ill have to look into a new CDN service, but the NPM package is up-to-date, and the dist/bundle.js file is updated, if you want to just download that and include it in your project for the short-term.

@foobar404 I am using npm package within Vue project, so it should be working if its implemented. If it has any value, here is my initialization code:

```
wave.value = new Wave(audio.value, output.value);
audio.value.addEventListener('canplay', async() => {
    wave.value.addAnimation(new wave.value.animations.Shine({
        rounded: true,
        fillColor: '#009BFF',
        lineColor: '#009BFF',
        lineWidth: 1,
        count: 140,
        diameter: 100,
        frequencyBand: 'mids',
    }));
canvas.value.width = 125;
canvas.value.height = 150;
});
```
