### ISSUE TITLE
IWaveOptions types and density (trying to reproduce shockwave)

### ISSUE THREAD

**Issue by acroyear** [foobar404/Wave.js#58]
(2.0 - I just upgraded today)

I'm trying to program some pre-sets for wave options and frequencies, and finding that IWaveOptions (and its enum for frequencyBand) are hidden away, meaning I have to go through an any or do hacks like `frequencyBand: f as "base" | "lows" | "mids" | "highs"` to get it to work.  I'm trying to reconstruct what was "shockwave" in version 1 (3 frequency waves, each a different color).

Also, Wave (the animation) is kind over-powered when not frequency-split.  I find that on a small canvas, it is often at 100% and so isn't really a very interesting visualization.

**Comment by acroyear** [comment]
Example - here's the volume of the audio at 100% - med and high are off the chart

[https://subfiresuite.com/_images/Screen%20Shot%202022-03-20%20at%202.12.24%20PM.png](https://subfiresuite.com/_images/Screen%20Shot%202022-03-20%20at%202.12.24%20PM.png)

here's the volume down to 10% - low is almost 0, med is reasonable, but high is totally flat-lined. If I include base (off when i took these screencaps), it is also flat-lined.

[https://subfiresuite.com/_images/Screen%20Shot%202022-03-20%20at%202.12.37%20PM.png](https://subfiresuite.com/_images/Screen%20Shot%202022-03-20%20at%202.12.37%20PM.png)

Yes, the colors are set to match the key colors of the album cover :)

**Comment by acroyear** [comment]
Arcs has a similar problem where the numbers for med and high tend to go into the 100% range very quickly.

**Comment by foobar404** [comment]
You're right, I knew this was an issue when building 2.0, but I thought most people wouldn't have this issue. I will likely push out a patch in a few days to fix this.

**Comment by acroyear** [comment]
https://github.com/foobar404/Wave.js/pull/61 - this addresses the typescript issue where a dev (me) can't easily declare my objects to match the animations' individual options.
