### ISSUE TITLE
Safari Issue: Can't find variable: AudioContext

### ISSUE THREAD

**Issue by CorfitzMe** [foobar404/Wave.js#7]
Apparently safari needs `webkit` prefix.
https://github.com/amaneureka/T-Rex/issues/5#issuecomment-217964069

**Comment by CorfitzMe** [comment]
Ps.. So nicely done this package.. Love it!

**Comment by foobar404** [comment]
Are you using the node, or the web version?

**Comment by CorfitzMe** [comment]
CDN. If I copy down the bundle and add `var AudioContext = window.AudioContext || window.webkitAudioContext;` at the very top, the error goes away... Unfortunately, this causes some audio issues, as to now, the sound is eliminated.. And - it is JUST Safari...

**Comment by CorfitzMe** [comment]
I just made a quick CodeSandBox: https://codesandbox.io/s/playing-with-the-wavejs-package-zfgio using the NPM package. If you open it up in Chrome - No issues, In ssafari, you'll see the error again regarding AudioContext.

**Comment by foobar404** [comment]
I'm having the same problem after adding the audio context fix, but I don't
have a apple device to debug the problem. Are there any errors after you
fix the problem?

**Comment by CorfitzMe** [comment]
Fixing one seemed to have created a new :P I have tested the bundle with the fix here https://codesandbox.io/s/snowy-snow-p569j?file=/bundle.js , and the error does indeed go away in Safari - though now weird stuff happens where the audio doesn't even play.

**Comment by foobar404** [comment]
Okay Ill be working on a solution in the next few days.

**Comment by CorfitzMe** [comment]
Have a look at #8 :D You may have to package the repo yourself for release. Not sure how to...

**Comment by foobar404** [comment]
Okay I setup a development workflow and uploaded my source files. Look at the bottom of the readme to see details on how to work with the source files. I also worked for a while on the ios issue. Im not sure if I solved the issue because I dont have anyway of testing but I did implement something that should of fixed it. The audioContext is muted by safari, and is only unmuted when a user gesture happens. But you must also create the audioContext when the user event happens, and try to play a sound so safari unmutes. Hopefully the issue is now solved.

**Comment by CorfitzMe** [comment]
Great stuff this.. I have had a little browse-through... I looked into the react-test - which is failing due to the `wave.fromElement` only accepting strings for IDs and finding the elements automatically, whereas the thought of being able to assign an actual element as parameter, may be a good idea - especially on the react side of things.. We should look further into that..

The Safari issue has been resolved, but testing on the iPhone doesn't seem to work well.. Not sure if this is a localhost issue or bug in code, so will get back to you on that.. Great job solving the Safari bug.. cheers..

**Comment by CorfitzMe** [comment]
Oh.. Guess we can actually close this issue now then
/close
