### ISSUE TITLE
The sound disappears!

### ISSUE THREAD

**Issue by vlad-salabun** [foobar404/Wave.js#73]
I really liked your library. And I want to use it in my pet project. I copied the code from your example, here it is:
https://jsfiddle.net/j6evzynt/

And there is no sound, and no errors, no visualization... Only seconds pass, like a sound is mute. 
What am I missing?

I check in Chrome and Mozilla, Windows and MacOS.

**Comment by vinikatyal** [comment]
Try this https://stackoverflow.com/questions/31308679/mediaelementaudiosource-outputs-zeros-due-to-cors-access-restrictions-local-mp3
